version: 3.1

services:
  springappcontainer:

    image: khagesh4/springappimage:1
    restart: always
    container: springappcontainer
    ports:
      8085:8080
    environments:
      MONGO_DB_HOSTNAME=mongo
      MONGO_INITDB_ROOT_USERNAME=devdb
      MONGO_INITDB_ROOT_PASSWORD=devdb@123
    workdir: /opt/app/
    depends on: mongo
    networks:
    - ksoverlay
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongo:
    image: mongoimage
    container: spring_mongo_container
    environments:
      MONGO_INITDB_ROOT_USERNAME=devdb
      MONGO_INITDB_ROOT_PASSWORD=devdb@123
    volumes:
    - mongoebsvol:/data/db
    restart: always
    networks:
    - ksoverlay

  volumes:
    mongoebsvol:
      driver: rexray/ebs
      external: 

  networks:
    ksbridge:
      driver: overlay
      external: 
